default:
  image:
    name: hashicorp/terraform:0.14.8
    entrypoint: [""]

variables:
  TF_ROOT: ${CI_PROJECT_DIR}

cache:
  paths:
    - ${TF_ROOT}/.terraform/
    - ${TF_ROOT}/.terraform.lock.hcl

stages:
  - init
  - validate
  - plan
  - apply

terraform-get:
  stage: init
  script: 
    - terraform init #get
    - terraform version

terraform-validate:
  stage: validate
  script:
    - terraform validate
    - terraform fmt #-check 

terraform-plan:
  stage: plan
  script: TF_LOG=DEBUG OS_DEBUG=1 terraform plan -out plan
  artifacts:
    name: plan
    paths:
      - ${TF_ROOT}/plan

terraform-apply:
  stage: apply
  only:
    - master
  script: 
    - terraform apply -auto-approve plan
    - terraform show
