default:
  image:
    name: hashicorp/terraform:0.15.4
    entrypoint: [""]

variables:
  TF_ROOT: ${CI_PROJECT_DIR}

cache:
  paths:
    - ${TF_ROOT}/.terraform/
    - ${TF_ROOT}/.terraform.lock.hcl

stages:
  - init
  - validate
  - plan
  - apply

terraform-get:
  stage: init
  script: 
    - terraform init
    - terraform version

terraform-validate:
  stage: validate
  script:
    - terraform validate
    - terraform fmt

terraform-plan:
  stage: plan
  script: 
    - apk add tzdata
    - terraform plan -out plan
  artifacts:
    name: plan
    paths:
      - ${TF_ROOT}/plan

terraform-apply:
  stage: apply
  only:
    - master
  script: 
    - terraform apply -parallelism 1 -auto-approve plan
    - terraform show
